questions = [
    "What is the capital of Australia? \nA: Sydney  \nB: Canberra  \nC: Melbourne  \nD: Brisbane",
    "Which planet is known as the Red Planet? \nA: Earth  \nB: Mars  \nC: Jupiter  \nD: Saturn",
    "Who is known as the father of modern physics? \nA: Isaac Newton  \nB: Albert Einstein  \nC: Galileo Galilei  \nD: Stephen Hawking",
    "Which is the smallest continent by area? \nA: Europe  \nB: Antarctica  \nC: Asia  \nD: Australia",
    "Which country is known as the Land of the Rising Sun? \nA: China  \nB: Japan  \nC: South Korea  \nD: Thailand",
    "What is the longest river in the world? \nA: Nile  \nB: Amazon  \nC: Yangtze  \nD: Mississippi",
    "Who wrote the play *Romeo and Juliet*? \nA: Charles Dickens  \nB: William Shakespeare  \nC: Jane Austen  \nD: Mark Twain",
    "What is the chemical symbol for Gold? \nA: Au  \nB: Ag  \nC: Gd  \nD: Go",
    "Which of the following is the largest mammal? \nA: Blue Whale  \nB: African Elephant  \nC: Giraffe  \nD: Polar Bear",
    "Which country is the world's largest by area? \nA: United States  \nB: Russia  \nC: China  \nD: Canada",
    "What does DNA stand for? \nA: Deoxyribonucleic Acid  \nB: Dioxyribonucleic Acid  \nC: Deoxyribonuclein Acid  \nD: Diatomic Ribonucleic Acid",
    "Which gas do plants absorb from the atmosphere? \nA: Oxygen  \nB: Carbon Dioxide  \nC: Nitrogen  \nD: Hydrogen",
    "Which city is known as the City of Love? \nA: Venice  \nB: Paris  \nC: London  \nD: Rome",
    "Which sport is known as the 'king of sports'? \nA: Cricket  \nB: Tennis  \nC: Soccer (Football)  \nD: Rugby",
    "Who painted the *Mona Lisa*? \nA: Vincent van Gogh  \nB: Leonardo da Vinci  \nC: Pablo Picasso  \nD: Claude Monet",
    "What is the freezing point of water in Celsius? \nA: 0°C  \nB: 32°C  \nC: 100°C  \nD: -32°C",
    "Which is the smallest country in the world by area? \nA: Monaco  \nB: Vatican City  \nC: Nauru  \nD: San Marino",
    "How many continents are there on Earth? \nA: 5  \nB: 6  \nC: 7  \nD: 8",
    "Which language is the most spoken in the world? \nA: English  \nB: Mandarin Chinese  \nC: Spanish  \nD: Hindi",
    "What is the capital of Canada? \nA: Toronto  \nB: Ottawa  \nC: Vancouver  \nD: Montreal",
    "Which planet is closest to the Sun? \nA: Earth  \nB: Venus  \nC: Mercury  \nD: Mars",
    "What is the national flower of India? \nA: Rose  \nB: Lotus  \nC: Jasmine  \nD: Sunflower"
]
